{"timestamp":"2025-09-17T17:15:05.895607","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-17T17:15:05.895764","level":"info","event":"Filling up the DagBag from /Users/rail/PracticalML/MLOps-practice/services/airflow/dags/data_pipeline_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-17T17:15:06.506411Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T17:15:06.506477Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T17:15:06.506626Z","level":"info","event":"Current task name:remove_nan","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T17:15:06.506649Z","level":"info","event":"Dag name:data_pipeline_dag","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T17:15:06.507638","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"FileNotFoundError","exc_value":"[Errno 2] No such file or directory: '/Users/rail/PracticalML/MLOps-practice/services/data/raw/train.csv'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/Users/rail/PracticalML/MLOps-practice/services/airflow/dags/data_pipeline_dag.py","lineno":19,"name":"remove_nan"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py","lineno":1026,"name":"read_csv"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py","lineno":620,"name":"_read"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py","lineno":1620,"name":"__init__"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/pandas/io/parsers/readers.py","lineno":1880,"name":"_make_engine"},{"filename":"/Users/rail/PracticalML/MLOps-practice/.venv/lib/python3.9/site-packages/pandas/io/common.py","lineno":873,"name":"get_handle"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-17T17:15:06.508020Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T17:15:06.508179Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T17:15:06.508208Z","level":"info","event":"Task:<Task(PythonOperator): remove_nan>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-17T17:15:06.508228Z","level":"info","event":"Failure caused by [Errno 2] No such file or directory: '/Users/rail/PracticalML/MLOps-practice/services/data/raw/train.csv'","chan":"stdout","logger":"task"}
